import os

AI_FEEDS = [
    {"name": "36氪", "url": "https://36kr.com/feed", "weight": 6, "lang": "zh",
     "source_name": "36氪", "source_type": "rss", "source_region": "CN", "source_priority": 75},
    {"name": "量子位", "url": "https://www.qbitai.com/feed", "weight": 6, "lang": "zh",
     "source_name": "量子位", "source_type": "rss", "source_region": "CN", "source_priority": 78},
    {"name": "机器之心", "url": "https://www.jiqizhixin.com/rss", "weight": 7, "lang": "zh",
     "source_name": "机器之心", "source_type": "rss", "source_region": "CN", "source_priority": 80},
    {"name": "InfoQ 中文", "url": "https://www.infoq.cn/feed", "weight": 6, "lang": "zh",
     "source_name": "InfoQ 中文", "source_type": "rss", "source_region": "CN", "source_priority": 78},
    {"name": "智东西", "url": "https://www.zhidx.com/feed", "weight": 6, "lang": "zh",
     "source_name": "智东西", "source_type": "rss", "source_region": "CN", "source_priority": 75},
    {"name": "Hacker News", "url": "https://hnrss.org/frontpage?count=20", "weight": 7, "lang": "en",
     "source_name": "Hacker News", "source_type": "rss", "source_region": "Global", "source_priority": 60},
    {"name": "TechCrunch AI", "url": "https://techcrunch.com/category/artificial-intelligence/feed/", "weight": 7, "lang": "en",
     "source_name": "TechCrunch AI", "source_type": "rss", "source_region": "Global", "source_priority": 78},
    {"name": "MIT Tech Review", "url": "https://www.technologyreview.com/topic/artificial-intelligence/feed/", "weight": 6, "lang": "en",
     "source_name": "MIT Tech Review", "source_type": "rss", "source_region": "Global", "source_priority": 80},
    {"name": "VentureBeat AI", "url": "https://venturebeat.com/category/ai/feed/", "weight": 6, "lang": "en",
     "source_name": "VentureBeat AI", "source_type": "rss", "source_region": "Global", "source_priority": 75},
    {"name": "The Decoder", "url": "https://the-decoder.com/feed/", "weight": 7, "lang": "en",
     "source_name": "The Decoder", "source_type": "rss", "source_region": "Global", "source_priority": 76},
    {"name": "Qwen 官方博客", "url": "https://qwenlm.github.io/blog/feed.xml", "weight": 8, "lang": "zh",
     "source_name": "Qwen 官方博客", "source_type": "rss", "source_region": "CN", "source_priority": 95, "status": "disabled", "deprecated": True},
    {"name": "InternLM 官方博客", "url": "https://internlm.github.io/blog/feed.xml", "weight": 8, "lang": "zh",
     "source_name": "InternLM 官方博客", "source_type": "rss", "source_region": "CN", "source_priority": 95, "status": "disabled", "deprecated": True},
    {"name": "阿里云开发者社区", "url": "https://developer.aliyun.com/rss", "weight": 8, "lang": "zh",
     "source_name": "阿里云开发者社区", "source_type": "rss", "source_region": "CN", "source_priority": 90, "status": "disabled", "deprecated": True},
    {"name": "腾讯云开发者社区", "url": "https://cloud.tencent.com/developer/rss", "weight": 8, "lang": "zh",
     "source_name": "腾讯云开发者社区", "source_type": "rss", "source_region": "CN", "source_priority": 90},
    {"name": "华为云开发者社区", "url": "https://developer.huaweicloud.com/rss", "weight": 8, "lang": "zh",
     "source_name": "华为云开发者社区", "source_type": "rss", "source_region": "CN", "source_priority": 90},
    {"name": "ModelScope 魔搭", "url": "https://modelscope.cn/rss", "weight": 8, "lang": "zh",
     "source_name": "ModelScope 魔搭", "source_type": "rss", "source_region": "CN", "source_priority": 90},
    {"name": "OSCHINA 开源中国", "url": "https://www.oschina.net/news/rss", "weight": 6, "lang": "zh",
     "source_name": "OSCHINA 开源中国", "source_type": "rss", "source_region": "CN", "source_priority": 75},
    {"name": "OpenAI News", "url": "https://openai.com/news/rss.xml", "weight": 9, "lang": "en",
     "source_name": "OpenAI 官方", "source_type": "rss", "source_region": "Global", "source_priority": 100, "max_entries": 40, "status": "stable", "tier": "A"},
    {"name": "Anthropic News", "url": "https://www.anthropic.com/news/rss.xml", "weight": 9, "lang": "en",
     "source_name": "Anthropic 官方", "source_type": "rss", "source_region": "Global", "source_priority": 100, "max_entries": 40, "status": "disabled", "deprecated": True},
    {"name": "Google AI Blog", "url": "https://blog.google/technology/ai/rss/", "weight": 9, "lang": "en",
     "source_name": "Google AI 官方", "source_type": "rss", "source_region": "Global", "source_priority": 100, "max_entries": 40, "status": "stable", "tier": "A"},
    {"name": "Google DeepMind", "url": "https://deepmind.google/blog/rss.xml", "weight": 9, "lang": "en",
     "source_name": "Google DeepMind 官方", "source_type": "rss", "source_region": "Global", "source_priority": 100, "max_entries": 40, "status": "stable", "tier": "A"},
    {"name": "Meta AI", "url": "https://ai.meta.com/blog/rss/", "weight": 8, "lang": "en",
     "source_name": "Meta AI 官方", "source_type": "rss", "source_region": "Global", "source_priority": 95, "max_entries": 40, "status": "disabled", "deprecated": True},
    {"name": "Microsoft AI", "url": "https://blogs.microsoft.com/ai/feed/", "weight": 8, "lang": "en",
     "source_name": "Microsoft AI 官方", "source_type": "rss", "source_region": "Global", "source_priority": 95, "max_entries": 40, "status": "disabled", "deprecated": True},
    {"name": "Hugging Face Blog", "url": "https://huggingface.co/blog/feed.xml", "weight": 8, "lang": "en",
     "source_name": "Hugging Face 官方", "source_type": "rss", "source_region": "Global", "source_priority": 95, "max_entries": 40, "status": "stable", "tier": "A"},
    {"name": "AndroidX Release Notes", "url": "https://developer.android.com/feeds/androidx-release-notes.xml", "weight": 8, "lang": "en",
     "source_name": "AndroidX 官方", "source_type": "rss", "source_region": "Global", "source_priority": 95, "max_entries": 40, "status": "unstable", "tier": "A"},
    {"name": "xAI SDK Releases", "url": "https://github.com/xai-org/xai-sdk-python/releases.atom", "weight": 8, "lang": "en",
     "source_name": "xAI 官方", "source_type": "github_release", "source_region": "Global", "source_priority": 95, "max_entries": 40, "status": "stable", "tier": "A"},
    {"name": "Volcengine Ark Releases", "url": "https://github.com/volcengine/ark-cli/releases.atom", "weight": 8, "lang": "zh",
     "source_name": "豆包/火山引擎官方", "source_type": "github_release", "source_region": "CN", "source_priority": 100, "max_entries": 40, "status": "stable", "tier": "A", "source_role": "first_party"},
    {"name": "Zhipu SDK Releases", "url": "https://github.com/MetaGLM/zhipuai-sdk-python-v4/releases.atom", "weight": 8, "lang": "zh",
     "source_name": "智谱官方", "source_type": "github_release", "source_region": "CN", "source_priority": 100, "max_entries": 40, "status": "stable", "tier": "A", "source_role": "first_party"},
    {"name": "MiniMax CLI Releases", "url": "https://github.com/MiniMax-AI/cli/releases.atom", "weight": 8, "lang": "en",
     "source_name": "MiniMax 官方", "source_type": "github_release", "source_region": "CN", "source_priority": 100, "max_entries": 40, "status": "stable", "tier": "A", "source_role": "first_party"},
    {"name": "Moonshot Kimi CLI Releases", "url": "https://github.com/MoonshotAI/kimi-cli/releases.atom", "weight": 8, "lang": "en",
     "source_name": "月之暗面官方", "source_type": "github_release", "source_region": "CN", "source_priority": 100, "max_entries": 40, "status": "stable", "tier": "A", "source_role": "first_party"},
    {"name": "Anthropic SDK Releases", "url": "https://github.com/anthropics/anthropic-sdk-python/releases.atom", "weight": 8, "lang": "en",
     "source_name": "Anthropic 官方", "source_type": "github_release", "source_region": "Global", "source_priority": 100, "max_entries": 40, "status": "stable", "tier": "A", "source_role": "first_party"},
    {"name": "Microsoft Semantic Kernel Releases", "url": "https://github.com/microsoft/semantic-kernel/releases.atom", "weight": 8, "lang": "en",
     "source_name": "Microsoft AI 官方", "source_type": "github_release", "source_region": "Global", "source_priority": 100, "max_entries": 40, "status": "stable", "tier": "A", "source_role": "first_party"},
    {"name": "Meta Llama Releases", "url": "https://github.com/meta-llama/llama-models/releases.atom", "weight": 8, "lang": "en",
     "source_name": "Meta AI 官方", "source_type": "github_release", "source_region": "Global", "source_priority": 100, "max_entries": 40, "status": "stable", "tier": "A", "source_role": "first_party"},
]

# First-party coverage registry (MVP metadata).  HTML entries are intentionally
# marked unsupported until a stable RSS/Atom/changelog adapter exists.
AI_FIRST_PARTY_SOURCES = [
    {"source_name": "Anthropic 官方", "source_type": "official", "region": "Global", "priority": 100,
     "fetch_method": "html", "url": "https://www.anthropic.com/news", "max_entries": 20, "status": "unstable_html"},
    {"source_name": "豆包/字节 AI 官方", "source_type": "official", "region": "CN", "priority": 100,
     "fetch_method": "html", "url": "https://www.doubao.com/chat/", "max_entries": 20, "status": "unstable_html"},
    {"source_name": "腾讯混元官方", "source_type": "official", "region": "CN", "priority": 100,
     "fetch_method": "github_release", "url": "https://github.com/Tencent-Hunyuan/Hy3/releases.atom", "max_entries": 20, "status": "unsupported", "watch_enabled": False},
    {"source_name": "腾讯混元官方", "source_type": "official", "region": "CN", "priority": 100,
     "fetch_method": "html", "url": "https://hunyuan.tencent.com/", "max_entries": 20, "status": "unstable_html"},
    {"source_name": "科大讯飞/星火官方", "source_type": "official", "region": "CN", "priority": 100,
     "fetch_method": "html", "url": "https://www.xfyun.cn/hera/404", "max_entries": 20, "status": "unsupported"},
    {"source_name": "Android 官方", "source_type": "official", "region": "Global", "priority": 95,
     "fetch_method": "html", "url": "https://blog.google/products-and-platforms/platforms/android/", "max_entries": 20, "status": "unstable_html"},
    {"source_name": "Manus 官方", "source_type": "official", "region": "Global", "priority": 95,
     "fetch_method": "html", "url": "https://manus.im/blog", "max_entries": 20, "status": "unstable_html"},
]
GITHUB_SOURCE = {
    "source_name": "GitHub",
    "source_type": "github",
    "source_region": "Global",
    "source_priority": 85,
}
GAMING_FEEDS = [
    {"name":'IGN',"url":'https://feeds.feedburner.com/ign/all',"weight":8,"lang":'en'},
    {"name":'PC Gamer',"url":'https://www.pcgamer.com/rss/',"weight":7,"lang":'en'},
    {"name":'Eurogamer',"url":'https://www.eurogamer.net/feed',"weight":7,"lang":'en'},
    {"name":'Gematsu',"url":'https://www.gematsu.com/feed',"weight":6,"lang":'en'},
    {"name":'Nintendo Life',"url":'https://www.nintendolife.com/feed',"weight":7,"lang":'en'},
    {"name":'机核网',"url":'https://www.gcores.com/rss',"weight":6,"lang":'zh'},
    {"name":'VG247',"url":'https://www.vg247.com/feed',"weight":6,"lang":'en'},
    {"name":'GamesIndustry',"url":'https://www.gamesindustry.biz/feed',"weight":6,"lang":'en'},
]
FRESHNESS_HALF_LIFE = 24
FRESHNESS_MAX_HOURS = 72
AI_HOT_KEYWORDS = [
    "gpt",
    "openai",
    "gemini",
    "claude",
    "llama",
    "deep learning",
    "transformer",
    "diffusion",
    "sora",
    "o1",
    "o3",
    "gpt-5",
    "reasoning",
    "nvidia",
    "h100",
    "ai chip",
    "agent",
    "multi-agent",
    "rag",
    "llm",
    "regulation",
    "alignment",
    "safety",
    "foundation model",
    "人工智能",
    "大模型",
    "深度学习",
]
GAMING_HOT_KEYWORDS = [
    "elden ring",
    "zelda",
    "gta",
    "cyberpunk",
    "witcher",
    "nintendo",
    "playstation",
    "xbox",
    "steam",
    "release date",
    "trailer",
    "gameplay",
    "diablo",
    "final fantasy",
    "call of duty",
    "unreal engine",
    "unity",
    "new game",
    "update",
    "patch",
    "expansion",
    "dlc",
    "remake",
    "remaster",
    "announced",
    "launch",
    "exclusive",
    "game pass",
    "游戏",
    "主机",
    "手游",
    "独立游戏",
    "任天堂",
    "索尼",
]
def TD(pairs):
    return "{" + ", ".join('"' + k + '": "' + v + '"' for k,v in pairs) + "}"
AI_TECH_TAGS = {"gpt":"GPT", "gpt-4":"GPT-4", "gpt-5":"GPT-5", "claude":"Claude", "gemini":"Gemini", "llama":"LLaMA", "transformer":"Transformer", "diffusion":"Diffusion", "llm":"LLM", "rag":"RAG", "agent":"Agent", "sora":"Sora", "o1":"o1", "o3":"o3", "nvidia":"NVIDIA", "gpu":"GPU", "reasoning":"Reasoning", "deep learning":"Deep Learning", "open source":"Open Source", "foundation model":"Foundation Model"}
AI_SOLUTION_TAGS = {"paper":"Research", "arxiv":"Preprint", "released":"Release", "launch":"Launch", "announced":"Announce", "beta":"Beta", "funding":"Funding", "partnership":"Partner", "benchmark":"Benchmark", "regulation":"Policy"}
AI_COMPANY_TAGS = {"openai":"OpenAI", "anthropic":"Anthropic", "google":"Google", "deepmind":"DeepMind", "microsoft":"MS", "meta":"Meta", "nvidia":"NVIDIA", "apple":"Apple", "baidu":"Baidu", "bytedance":"ByteDance", "deepseek":"DeepSeek"}
GAMING_TECH_TAGS = {"unreal engine":"Unreal", "unity":"Unity", "dlss":"DLSS", "vr":"VR", "indie":"Indie", "aaa":"AAA", "dlc":"DLC", "remake":"Remake", "open world":"Open World", "rpg":"RPG", "fps":"FPS", "expansion":"Expansion", "game pass":"Game Pass"}
GAMING_COMPANY_TAGS = {"nintendo":"Nintendo", "sony":"Sony", "playstation":"PS", "xbox":"Xbox", "square enix":"Square Enix", "ubisoft":"Ubisoft", "ea":"EA", "activision":"Activision", "blizzard":"Blizzard", "valve":"Valve", "steam":"Steam", "rockstar":"Rockstar", "capcom":"Capcom"}
AI_ZH_TECH_TAGS = {'人工智能': 'AI', '大模型': 'LLM', '深度学习': 'Deep Learning', '研究': 'Research', '开源': 'Open Source', '算力': 'Compute'}
AI_ZH_COMPANY_TAGS = {'百度': 'Baidu', '腾讯': 'Tencent', '阿里': 'Alibaba', '字节': 'ByteDance', '华为': 'Huawei'}
GAMING_ZH_TECH_TAGS = {'游戏': 'Game', '主机': 'Console', '手游': 'Mobile', '电竞': 'eSports', '独立': 'Indie'}
GAMING_ZH_COMPANY_TAGS = {'任天堂': 'Nintendo', '索尼': 'Sony', '微软': 'Microsoft', '网易': 'NetEase', '米哈': 'miHoYo'}
ZH_TYPE_MAP = [
    (['研究', '论文'], '研究进展'),
    (['发布', '更新'], '产品动态'),
    (['融资', '合作'], '商业动态'),
    (['开源', 'GitHub'], '开源项目'),
]
DATA_DIR = os.path.join(os.path.dirname(__file__), 'data')
AI_DATA_FILE = os.path.join(DATA_DIR, 'news_ai.json')
GAMING_DATA_FILE = os.path.join(DATA_DIR, 'news_gaming.json')
REFRESH_INTERVAL_MINUTES = 30
